# Generated by Django 4.2.5 on 2024-09-11 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_invited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invited_by',
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='admin',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
