# Generated by Django 4.2.5 on 2024-09-24 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_invited_by_userinvitation_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_color', models.CharField(default='#000000', max_length=7)),
                ('button_color', models.CharField(default='#007bff', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('points_color', models.CharField(default='#007bff', max_length=7)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
