# Generated by Django 4.2.5 on 2024-09-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customizationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationsettings',
            name='navbar_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
