# Generated by Django 4.2.5 on 2024-10-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customizationsettings_navbar_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizationsettings',
            name='background_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='customizationsettings',
            name='button_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='customizationsettings',
            name='heading_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='customizationsettings',
            name='navbar_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='customizationsettings',
            name='points_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
