# Generated by Django 4.2.5 on 2024-10-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customizationsettings_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizationsettings',
            name='navbar_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
