# Generated by Django 4.2.5 on 2024-09-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_video_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
