# Generated by Django 4.2.5 on 2024-09-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_lesson_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['position']},
        ),
    ]
